# Numpy Project :- Student Result Analysis

##### **Description About Data**
There is a 'students_marks.csv' file which contains data of 100 students.
There are 100 rows where every row representing a student data. 
There are four columns where first column contains roll number and 
next three columns contains marks of maths, physics and chemistry.

**Importing the numpy library**

In [1]:
import numpy as np

**Read the data from csv file into numpy array**

In [2]:
students_data = np.loadtxt("students_marks.csv", delimiter = ",")

**Find the shape of data**

In [3]:
students_data.shape

(100, 4)

**Display first 5 rows of data**

In [4]:
print(students_data[:5])

[[101.  81.  75.  68.]
 [102.  42.  55.  49.]
 [103.  90.  88.  92.]
 [104.  67.  71.  65.]
 [105.  33.  40.  37.]]


**Find the total of marks of each student**

In [5]:
total_marks = students_data[:,1:].sum(axis = 1)
print(total_marks)

[224. 146. 270. 203. 110. 239. 178. 283. 215. 263. 148. 193. 240. 297.
 124. 219. 171. 275. 207. 245. 140. 207. 286. 185. 253. 118. 227. 270.
 162. 245. 207. 131. 279. 233. 158. 258. 198. 292. 130. 231. 269. 179.
 208. 273. 111. 247. 188. 219. 287. 152. 238. 204. 167. 268. 127. 239.
 259. 143. 211. 280. 183. 244. 193. 294. 120. 224. 262. 161. 205. 270.
 130. 250. 200. 232. 286. 149. 241. 214. 173. 277. 115. 225. 267. 155.
 256. 192. 217. 292. 164. 235. 203. 274. 140. 262. 214. 176. 283. 124.
 247. 208.]


**Add a new column that will store the total of marks of each student**

In [6]:
print(total_marks.reshape(1, -1))

[[224. 146. 270. 203. 110. 239. 178. 283. 215. 263. 148. 193. 240. 297.
  124. 219. 171. 275. 207. 245. 140. 207. 286. 185. 253. 118. 227. 270.
  162. 245. 207. 131. 279. 233. 158. 258. 198. 292. 130. 231. 269. 179.
  208. 273. 111. 247. 188. 219. 287. 152. 238. 204. 167. 268. 127. 239.
  259. 143. 211. 280. 183. 244. 193. 294. 120. 224. 262. 161. 205. 270.
  130. 250. 200. 232. 286. 149. 241. 214. 173. 277. 115. 225. 267. 155.
  256. 192. 217. 292. 164. 235. 203. 274. 140. 262. 214. 176. 283. 124.
  247. 208.]]


In [7]:
print(total_marks.reshape(-1, 1))

[[224.]
 [146.]
 [270.]
 [203.]
 [110.]
 [239.]
 [178.]
 [283.]
 [215.]
 [263.]
 [148.]
 [193.]
 [240.]
 [297.]
 [124.]
 [219.]
 [171.]
 [275.]
 [207.]
 [245.]
 [140.]
 [207.]
 [286.]
 [185.]
 [253.]
 [118.]
 [227.]
 [270.]
 [162.]
 [245.]
 [207.]
 [131.]
 [279.]
 [233.]
 [158.]
 [258.]
 [198.]
 [292.]
 [130.]
 [231.]
 [269.]
 [179.]
 [208.]
 [273.]
 [111.]
 [247.]
 [188.]
 [219.]
 [287.]
 [152.]
 [238.]
 [204.]
 [167.]
 [268.]
 [127.]
 [239.]
 [259.]
 [143.]
 [211.]
 [280.]
 [183.]
 [244.]
 [193.]
 [294.]
 [120.]
 [224.]
 [262.]
 [161.]
 [205.]
 [270.]
 [130.]
 [250.]
 [200.]
 [232.]
 [286.]
 [149.]
 [241.]
 [214.]
 [173.]
 [277.]
 [115.]
 [225.]
 [267.]
 [155.]
 [256.]
 [192.]
 [217.]
 [292.]
 [164.]
 [235.]
 [203.]
 [274.]
 [140.]
 [262.]
 [214.]
 [176.]
 [283.]
 [124.]
 [247.]
 [208.]]


In [8]:
print(total_marks)

[224. 146. 270. 203. 110. 239. 178. 283. 215. 263. 148. 193. 240. 297.
 124. 219. 171. 275. 207. 245. 140. 207. 286. 185. 253. 118. 227. 270.
 162. 245. 207. 131. 279. 233. 158. 258. 198. 292. 130. 231. 269. 179.
 208. 273. 111. 247. 188. 219. 287. 152. 238. 204. 167. 268. 127. 239.
 259. 143. 211. 280. 183. 244. 193. 294. 120. 224. 262. 161. 205. 270.
 130. 250. 200. 232. 286. 149. 241. 214. 173. 277. 115. 225. 267. 155.
 256. 192. 217. 292. 164. 235. 203. 274. 140. 262. 214. 176. 283. 124.
 247. 208.]


In [9]:
total_marks = total_marks.reshape(-1, 1)
print(total_marks)

[[224.]
 [146.]
 [270.]
 [203.]
 [110.]
 [239.]
 [178.]
 [283.]
 [215.]
 [263.]
 [148.]
 [193.]
 [240.]
 [297.]
 [124.]
 [219.]
 [171.]
 [275.]
 [207.]
 [245.]
 [140.]
 [207.]
 [286.]
 [185.]
 [253.]
 [118.]
 [227.]
 [270.]
 [162.]
 [245.]
 [207.]
 [131.]
 [279.]
 [233.]
 [158.]
 [258.]
 [198.]
 [292.]
 [130.]
 [231.]
 [269.]
 [179.]
 [208.]
 [273.]
 [111.]
 [247.]
 [188.]
 [219.]
 [287.]
 [152.]
 [238.]
 [204.]
 [167.]
 [268.]
 [127.]
 [239.]
 [259.]
 [143.]
 [211.]
 [280.]
 [183.]
 [244.]
 [193.]
 [294.]
 [120.]
 [224.]
 [262.]
 [161.]
 [205.]
 [270.]
 [130.]
 [250.]
 [200.]
 [232.]
 [286.]
 [149.]
 [241.]
 [214.]
 [173.]
 [277.]
 [115.]
 [225.]
 [267.]
 [155.]
 [256.]
 [192.]
 [217.]
 [292.]
 [164.]
 [235.]
 [203.]
 [274.]
 [140.]
 [262.]
 [214.]
 [176.]
 [283.]
 [124.]
 [247.]
 [208.]]


In [10]:
students_data = np.concatenate((students_data, total_marks), axis = 1)

**Display first 5 rows of data with newly added column for total of marks**

In [11]:
print(students_data[:5])

[[101.  81.  75.  68. 224.]
 [102.  42.  55.  49. 146.]
 [103.  90.  88.  92. 270.]
 [104.  67.  71.  65. 203.]
 [105.  33.  40.  37. 110.]]


**Find the average of marks of each student**

In [12]:
average_marks = students_data[:,1:-1].mean(axis = 1).round(2)
print(average_marks)

[74.67 48.67 90.   67.67 36.67 79.67 59.33 94.33 71.67 87.67 49.33 64.33
 80.   99.   41.33 73.   57.   91.67 69.   81.67 46.67 69.   95.33 61.67
 84.33 39.33 75.67 90.   54.   81.67 69.   43.67 93.   77.67 52.67 86.
 66.   97.33 43.33 77.   89.67 59.67 69.33 91.   37.   82.33 62.67 73.
 95.67 50.67 79.33 68.   55.67 89.33 42.33 79.67 86.33 47.67 70.33 93.33
 61.   81.33 64.33 98.   40.   74.67 87.33 53.67 68.33 90.   43.33 83.33
 66.67 77.33 95.33 49.67 80.33 71.33 57.67 92.33 38.33 75.   89.   51.67
 85.33 64.   72.33 97.33 54.67 78.33 67.67 91.33 46.67 87.33 71.33 58.67
 94.33 41.33 82.33 69.33]


In [13]:
average_marks = average_marks.reshape(-1, 1)
print(average_marks)

[[74.67]
 [48.67]
 [90.  ]
 [67.67]
 [36.67]
 [79.67]
 [59.33]
 [94.33]
 [71.67]
 [87.67]
 [49.33]
 [64.33]
 [80.  ]
 [99.  ]
 [41.33]
 [73.  ]
 [57.  ]
 [91.67]
 [69.  ]
 [81.67]
 [46.67]
 [69.  ]
 [95.33]
 [61.67]
 [84.33]
 [39.33]
 [75.67]
 [90.  ]
 [54.  ]
 [81.67]
 [69.  ]
 [43.67]
 [93.  ]
 [77.67]
 [52.67]
 [86.  ]
 [66.  ]
 [97.33]
 [43.33]
 [77.  ]
 [89.67]
 [59.67]
 [69.33]
 [91.  ]
 [37.  ]
 [82.33]
 [62.67]
 [73.  ]
 [95.67]
 [50.67]
 [79.33]
 [68.  ]
 [55.67]
 [89.33]
 [42.33]
 [79.67]
 [86.33]
 [47.67]
 [70.33]
 [93.33]
 [61.  ]
 [81.33]
 [64.33]
 [98.  ]
 [40.  ]
 [74.67]
 [87.33]
 [53.67]
 [68.33]
 [90.  ]
 [43.33]
 [83.33]
 [66.67]
 [77.33]
 [95.33]
 [49.67]
 [80.33]
 [71.33]
 [57.67]
 [92.33]
 [38.33]
 [75.  ]
 [89.  ]
 [51.67]
 [85.33]
 [64.  ]
 [72.33]
 [97.33]
 [54.67]
 [78.33]
 [67.67]
 [91.33]
 [46.67]
 [87.33]
 [71.33]
 [58.67]
 [94.33]
 [41.33]
 [82.33]
 [69.33]]


**Add a new column that will store the average of marks of each student**

In [14]:
students_data = np.concatenate((students_data, average_marks), axis = 1)

**Display first 5 rows of data with newly added column for average of marks**

In [15]:
print(students_data[:5])

[[101.    81.    75.    68.   224.    74.67]
 [102.    42.    55.    49.   146.    48.67]
 [103.    90.    88.    92.   270.    90.  ]
 [104.    67.    71.    65.   203.    67.67]
 [105.    33.    40.    37.   110.    36.67]]


**Find the average of marks of maths subject**

In [16]:
print("Average marks of maths:", students_data[:, 1].mean().round(2))

Average marks of maths: 70.42


**Find the average of marks of physics subject**

In [17]:
print("Average marks of physics:", students_data[:, 2].mean().round())

Average marks of physics: 71.0


**Find the average of marks of chemistry subject**

In [18]:
print("Average marks of chemistry:", students_data[:, 3].mean().round())

Average marks of chemistry: 71.0


**Find the highest marks in maths subject**

In [19]:
print("Highest marks of maths:", int(students_data[:,1].max().round()))

Highest marks of maths: 99


**Find the highest marks in physics subject**

In [20]:
print("Highest marks of physics:", int(students_data[:,2].max().round()))

Highest marks of physics: 100


**Find the highest marks in chemistry subject**

In [21]:
print("Highest marks of chemistry:", int(students_data[:,3].max().round()))

Highest marks of chemistry: 99


**Find the lowest marks in maths subject**

In [22]:
print("Lowest marks of maths:", int(students_data[:,1].min().round()))

Lowest marks of maths: 33


**Find the lowest marks in physics subject**

In [23]:
print("Lowest marks of physics:", int(students_data[:,2].min().round()))

Lowest marks of physics: 40


**Find the lowest marks in chemistry subject**

In [24]:
print("Lowest marks of chemistry:", int(students_data[:,3].min().round()))

Lowest marks of chemistry: 36


**Count the number of students who have scored more than or equal to 90 marks in maths subject**

In [25]:
print("Number of students who have scored more than or equal to 90 marks in maths subject:", 
students_data[:,1][students_data[:,1] >= 90].size)

Number of students who have scored more than or equal to 90 marks in maths subject: 20


**Count the number of students who have scored more than or equal to 90 marks in physics subject**

In [26]:
print("Number of students who have scored more than or equal to 90 marks in physics subject:", 
students_data[:,2][students_data[:,2] >= 90].size)

Number of students who have scored more than or equal to 90 marks in physics subject: 13


**Count the number of students who have scored average marks more than or equal to 60**

In [27]:
print("Number of students who have scored average marks more than or equal to 60:", 
students_data[:,5][students_data[:,5] >= 60].size)

Number of students who have scored average marks more than or equal to 60: 71


**Count the number of students who have scored average marks less than 50**

In [28]:
print("Number of students who have scored average marks less than 50:", 
len(students_data[:,5][students_data[:,5] < 50]))

Number of students who have scored average marks less than 50: 17


**Count the number of students who have scored average marks between 80 and 90**

In [29]:
print("Number of students who have scored average marks between 80 and 90:",
len(students_data[:,5][(students_data[:,5] >= 80) & (students_data[:,5] <= 90)]))

Number of students who have scored average marks between 80 and 90: 21


**Count the number of students who have scored marks more than or equal to 90 in all subjects**

In [30]:
students_scored_more_than_or_equal_to_90_in_all_subjects = students_data[
(students_data[:,1] >= 90) & (students_data[:,2] >= 90) & (students_data[:,3] >= 90)]
print(students_scored_more_than_or_equal_to_90_in_all_subjects)

[[108.    95.    91.    97.   283.    94.33]
 [114.    99.   100.    98.   297.    99.  ]
 [123.    97.    93.    96.   286.    95.33]
 [133.    94.    90.    95.   279.    93.  ]
 [138.    98.    95.    99.   292.    97.33]
 [149.    96.    94.    97.   287.    95.67]
 [160.    95.    91.    94.   280.    93.33]
 [164.    99.    97.    98.   294.    98.  ]
 [175.    97.    93.    96.   286.    95.33]
 [180.    94.    90.    93.   277.    92.33]
 [188.    98.    95.    99.   292.    97.33]
 [197.    96.    92.    95.   283.    94.33]]


In [31]:
print("Number of students who have scored marks more than or equal to 90 in all subjects:", 
len(students_scored_more_than_or_equal_to_90_in_all_subjects))

Number of students who have scored marks more than or equal to 90 in all subjects: 12


**Count the number of students who have scored marks more than or equal to 90 in any subject**

In [32]:
students_scored_more_than_or_equal_to_90_in_any_subjects = students_data[
(students_data[:,1] >= 90) | (students_data[:,2] >= 90) | (students_data[:,3] >= 90)]
print(students_scored_more_than_or_equal_to_90_in_any_subjects)

[[103.    90.    88.    92.   270.    90.  ]
 [108.    95.    91.    97.   283.    94.33]
 [110.    88.    85.    90.   263.    87.67]
 [114.    99.   100.    98.   297.    99.  ]
 [118.    92.    89.    94.   275.    91.67]
 [123.    97.    93.    96.   286.    95.33]
 [128.    91.    86.    93.   270.    90.  ]
 [133.    94.    90.    95.   279.    93.  ]
 [138.    98.    95.    99.   292.    97.33]
 [141.    89.    92.    88.   269.    89.67]
 [144.    93.    89.    91.   273.    91.  ]
 [149.    96.    94.    97.   287.    95.67]
 [154.    90.    87.    91.   268.    89.33]
 [160.    95.    91.    94.   280.    93.33]
 [164.    99.    97.    98.   294.    98.  ]
 [170.    92.    88.    90.   270.    90.  ]
 [175.    97.    93.    96.   286.    95.33]
 [180.    94.    90.    93.   277.    92.33]
 [183.    91.    87.    89.   267.    89.  ]
 [188.    98.    95.    99.   292.    97.33]
 [192.    93.    89.    92.   274.    91.33]
 [197.    96.    92.    95.   283.    94.33]]


In [33]:
print("Number of students who have scored marks more than or equal to 90 in any subject:", 
len(students_scored_more_than_or_equal_to_90_in_any_subjects))

Number of students who have scored marks more than or equal to 90 in any subject: 22


**Saving the Students Result Analysis Data to the 'students_result.csv' file**

In [34]:
np.savetxt('student_result.csv', students_data, delimiter = ',', fmt = ["%d", "%d", "%d", "%d", "%d", "%.2f"], 
header = "Roll Number,Maths Marks,Physics Marks,Chemistry Marks,Total Marks,Average Marks", comments="")
print("Student Result is saved successfully")

Student Result is saved successfully
